version: '3.9'

services:
  api:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - 5058:5058
    # networks:
    #   - handlelistenet

    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:5058/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  webapp:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    environment:
      API_URL: api
    ports:
      - 4000:4000
    depends_on:
      - api
    links: 
      - api
    # networks:
    #   - handlelistenet
    

networks:
  handlelistenet:
